# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Recipe for Intelligence
tagline:             coding, machine learning and other stuff
url:                 http://loganyc1934.github.io
paginate:            1
baseurl:             ""

highlighter: rouge
# Build settings
markdown: kramdown
markdown_ext: markdown,mkdown,mkdn,mkd,md

comments: True
# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Logan Yang
  url:               https://twitter.com/chaololo
  email:             lolo.yang86@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/loganyc1934

# navigation bar
pages_list:       
  About: '/about'
  Archive: '/archive'

gems: [jekyll-paginate]